export * from './groupsActions';
export * from './studentsActions';

export const ACTIONS_NAMES = {
  GROUPS_GET_ON_PERIOD: 'GROUPS_GET_ON_PERIOD',
  GROUPS_RECIVE_BY_TEACHER: 'GROUPS_RECIVE_BY_TEACHER',
  GROUPS_GET_BY_TEACHER: 'GROUPS_GET_BY_TEACHER',
  GROUPS_SET_LESSON: 'GROUPS_SET_LESSON',
  STUDENTS_GET_IN_GROUP: 'STUDENTS_GET_IN_GROUP'
};