export * from './groupsActions';
export * from './studentsActions';
export * from './authActions';
export * from './periodAction';
export * from './lessonsActions';

export const ACTIONS_NAMES = {
  GROUPS_GET_ON_PERIOD: 'GROUPS_GET_ON_PERIOD',
  GROUPS_RECIVE_BY_TEACHER: 'GROUPS_RECIVE_BY_TEACHER',
  GROUPS_GET_BY_TEACHER: 'GROUPS_GET_BY_TEACHER',
  GROUPS_SET_CURRENT: 'GROUPS_SET_CURRENT',
  STUDENTS_GET_IN_GROUP: 'STUDENTS_GET_IN_GROUP',
  STUDENTS_IN_JOURNAL_BY_GROUP: 'STUDENTS_IN_JOURNAL_BY_GROUP',
  AUTH_GET_EMPLOYEES: 'AUTH_GET_EMPLOYEES',
  AUTH_SELECT_EMPLOYEE: 'AUTH_SELECT_EMPLOYEE',
  AUTH_GET_USER: 'AUTH_GET_USER',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  PERIOD_GET_BY_USER: 'PERIOD_GET_BY_USER',
  LESSON_GET_BY_GROUPS_FOR_TEACHER: 'LESSON_GET_BY_GROUPS_FOR_TEACHER',
  LESSON_SET_CURRENT: 'LESSON_SET_CURRENT',
  LESSON_GET_JOURNAL_BY_LESSON: 'LESSON_GET_JOURNAL_BY_LESSON',
  LESSON_NEW_JOURNAL: 'LESSON_NEW_JOURNAL',
  LESSON_SET_CURRENT_JOURNAL: 'LESSON_SET_CURRENT_JOURNAL',
  LESSON_SET_EVALUATION: 'LESSON_SET_EVALUATION'
};